UPDATE Profesor SET Clases = 'Trazo Plano de Prendas Femeninas, Coordinación de Eventos de Moda, Conceptos y Tendencias de la Moda II' WHERE IdProfesor = 'P001';
UPDATE Profesor SET Clases = 'Taller de Diseño; Proyecto Integrador, Instalaciones, Patronaje de Prendas Femeninas' WHERE IdProfesor = 'P002';
UPDATE Profesor SET Clases = 'Modelos y Prototipos de Artículos Decorativos, Conceptos y Tendencias de la Moda I, Arquitectura Sustentable' WHERE IdProfesor = 'P003';
UPDATE Profesor SET Clases = 'Diseño de Joyería, Ergonomía, Modelado en Maniquí I' WHERE IdProfesor = 'P004';
UPDATE Profesor SET Clases = 'Textiles, Taller de Diseño de Espacios Turísticos, Desarrollo de Proyecto Integrador ' WHERE IdProfesor = 'P005';
UPDATE Profesor SET Clases = 'Patronaje de Prendas Básicas, Historia de la Arquitectura II, Trazo Plano de Alta Costura' WHERE IdProfesor = 'P006';
UPDATE Profesor SET Clases = 'Trazo Plano de Sastrería para Caballero, Taller Experimental de Moda, Materiales Textiles' WHERE IdProfesor = 'P007';
UPDATE Profesor SET Clases = 'Ambientación de Planos Arquitectónicos, Herramientas Industriales, Patronaje de Prendas Masculinas' WHERE IdProfesor = 'P008';
UPDATE Profesor SET Clases = 'Técnicas de Joyería Fina, Taller de Lectura y Redacción, Diseño de Moda Asistido por Computadora' WHERE IdProfesor = 'P009';
UPDATE Profesor SET Clases = 'Modelación Digital II, Optimización de Punto de Venta, Desarrollo Empresarial' WHERE IdProfesor = 'P010';
UPDATE Profesor SET Clases = 'Modelos y Prototipos de Mobiliario, Sistemas de Producción, Confección de Prendas Básicas' WHERE IdProfesor = 'P011';
UPDATE Profesor SET Clases = 'Herramientas y Puntadas Básicas, Confección de Sastrería para Dama, Taller de Diseño del Espacio Habitable' WHERE IdProfesor = 'P012';
UPDATE Profesor SET Clases = 'Taller de Diseño de Espacios Comerciales, Trazo Plano de Lencería y Traje de Baño, Graduación de Tallas' WHERE IdProfesor = 'P013';
UPDATE Profesor SET Clases = 'Trazo Plano de Sastrería para Dama, Ilustración Técnica de la Moda II, Fundamentos del Administración' WHERE IdProfesor = 'P014';
UPDATE Profesor SET Clases = 'Geometría Descriptiva, Fundamentos del Diseño, Patronaje de Prendas Infantiles' WHERE IdProfesor = 'P015';
UPDATE Profesor SET Clases = 'Trazo Plano de Prendas Masculinas, Historia del Mueble, Ilustración Gráfica Digital' WHERE IdProfesor = 'P016';
UPDATE Profesor SET Clases = 'Metodología para el Desarrollo de una Colección, Fundamentos de Admnistración, Conceptos y Tendencias de Moda II ' WHERE IdProfesor = 'P017';
UPDATE Profesor SET Clases = 'Confección de Prendas Femeninas, Historia del Arte, Desarrollo de Proyecto Integrador' WHERE IdProfesor = 'P018';
UPDATE Profesor SET Clases = 'Historia de la Moda, Patronaje de Alta Costura, Domótica' WHERE IdProfesor = 'P019';
UPDATE Profesor SET Clases = 'Edición Digital de Imagen , Psicología del Espacio, Taller de Diseño de Espacios Comunitarios' WHERE IdProfesor = 'P020';
UPDATE Profesor SET Clases = 'Modelación Digital I, Comunicación Efectiva, Análisis de Culturas' WHERE IdProfesor = 'P021';
UPDATE Profesor SET Clases = 'Conceptos y Tendencias de Moda I, Introducción al Diseño y Arquitectura de Interiores, Confección de Lencería y Traje de Baño' WHERE IdProfesor = 'P022';
UPDATE Profesor SET Clases = 'Patronaje de Sastrería para Dama, Modelado de Maniquí II, Trazo Plano de Prendas Básicas' WHERE IdProfesor = 'P023';
UPDATE Profesor SET Clases = 'Aplicación Textil I, Fundamentos de Mercadotecnia, Patronaje de Lencería y Traje de Baño' WHERE IdProfesor = 'P024';
UPDATE Profesor SET Clases = 'Modelado en Maniquí II, Renderización y Recorridos Virtuales, Confección de Prendas Masculinas' WHERE IdProfesor = 'P025';
UPDATE Profesor SET Clases = 'Teoría del Color, Costos y Presupuestos, Trazo Plano de Prendas Infantiles' WHERE IdProfesor = 'P026';
UPDATE Profesor SET Clases = 'Apreciación Estética de la Arquitectura Mexicana, Imagen Corporativa, Aplicación Textil II' WHERE IdProfesor = 'P027';
UPDATE Profesor SET Clases = 'Teoría del Diseño de Interiores, Modelado de Maniquí I, Materiales Pétreos y Madera' WHERE IdProfesor = 'P028';
UPDATE Profesor SET Clases = 'Taller de Dibujo Arquitectónico, Modelos y Maquetas, Metodología del Diseño' WHERE IdProfesor = 'P029';
UPDATE Profesor SET Clases = 'Diseño de Accesorios, Recubrimientos y Acabados, Procedimientos de Construcción' WHERE IdProfesor = 'P030';
UPDATE Profesor SET Clases = 'Técnicas de Representación, Historia de la Arquitectura I, Portafolio Profesional' WHERE IdProfesor = 'P031';
UPDATE Profesor SET Clases = 'Ilustración Técnica de la Moda III, Confección de Sastrería para Caballero, Edición Digital de Imagen' WHERE IdProfesor = 'P032';
UPDATE Profesor SET Clases = 'Diseño de Paisaje, Desarrollo del Pensamiento Creativo, Mercadotecnia de la Moda' WHERE IdProfesor = 'P033';
UPDATE Profesor SET Clases = 'Confección de Alta Costura, Ilustración Técnica de la Moda I, Dibujo y Modelación Digital' WHERE IdProfesor = 'P034';
UPDATE Profesor SET Clases = 'Ética Profesional, Taller de Diseño de Viviendas Residenciales, Taller de Diseño de Construcciones Efímeras' WHERE IdProfesor = 'P035';
UPDATE Profesor SET Clases = 'Confección de Prendas Infantiles, Iluminación y Acústica, Teoría de Color ' WHERE IdProfesor = 'P036';
UPDATE Profesor SET Clases = 'Dibujo Arquitectónico Digital' WHERE IdProfesor = 'P037';
UPDATE Profesor SET Clases = 'Metodología para el Desarrollo de una Colección, Taller de Diseño de Espacios Comerciales, Patronaje de Prendas Masculinas' WHERE IdProfesor = 'P038';
UPDATE Profesor SET Clases = 'Desarrollo de Proyecto Integrador , Imagen Corporativa, Renderización y Recorridos Virtuales' WHERE IdProfesor = 'P039';
UPDATE Profesor SET Clases = 'Procedimientos de Construcción, Mercadotecnia de la Moda, Historia de la Moda' WHERE IdProfesor = 'P040';
UPDATE Profesor SET Clases = 'Taller de Dibujo Arquitectónico, Materiales Pétreos y Madera, Fundamentos de Admnistración' WHERE IdProfesor = 'P041';
UPDATE Profesor SET Clases = 'Taller Experimental de Moda, Trazo Plano de Lencería y Traje de Baño, Modelación Digital II' WHERE IdProfesor = 'P042';
UPDATE Profesor SET Clases = 'Materiales Textiles, Análisis de Culturas, Confección de Prendas Infantiles' WHERE IdProfesor = 'P043';
UPDATE Profesor SET Clases = 'Modelado en Maniquí I, Textiles, Trazo Plano de Prendas Femeninas' WHERE IdProfesor = 'P044';
UPDATE Profesor SET Clases = 'Apreciación Estética de la Arquitectura Mexicana, Taller de Diseño; Proyecto Integrador, Fundamentos del Administración' WHERE IdProfesor = 'P045';
UPDATE Profesor SET Clases = 'Costos y Presupuestos, Conceptos y Tendencias de la Moda I, Fundamentos del Diseño' WHERE IdProfesor = 'P046';
UPDATE Profesor SET Clases = 'Trazo Plano de Prendas Infantiles, Confección de Sastrería para Dama, Edición Digital de Imagen' WHERE IdProfesor = 'P047';
UPDATE Profesor SET Clases = 'Comunicación Efectiva, Conceptos y Tendencias de Moda II , Introducción al Diseño y Arquitectura de Interiores' WHERE IdProfesor = 'P048';
UPDATE Profesor SET Clases = 'Confección de Lencería y Traje de Baño, Confección de Prendas Femeninas, Modelado de Maniquí I' WHERE IdProfesor = 'P049';
UPDATE Profesor SET Clases = 'Confección de Alta Costura, Técnicas de Representación, Metodología del Diseño' WHERE IdProfesor = 'P050';